parameters:
    odigo.factory.abstract.class: OdigoBundle\Factory\AbstractFactory
    odigo.factory.userbean.class: OdigoBundle\Factory\UserBeans\UserBeanFactory
    odigo.factory.userskillbean.class: OdigoBundle\Factory\UserBeans\UserSkillBeanFactory
    odigo.factory.userbeanwithtemplate.class: OdigoBundle\Factory\UserBeansWithTemplate\UserBeanWithTemplateFactory
    odigo.factory.userskillbeanwithtemplate.class: OdigoBundle\Factory\UserBeansWithTemplate\UserSkillBeanWithTemplateFactory
    odigo.factory.createagent.class: OdigoBundle\Factory\Actions\CreateAgentStructFactory
    odigo.factory.createwithtemplate.class: OdigoBundle\Factory\Actions\CreateWithTemplateStructFactory
    odigo.factory.export.class: OdigoBundle\Factory\Actions\ExportStructFactory
    odigo.factory.deleteuser.class: OdigoBundle\Factory\Actions\DeleteUserStructFactory
    odigo.service.client.class: OdigoBundle\Services\OdigoClientService

services:
    odigo.factory.abstract:
        class: %odigo.factory.abstract.class%
        abstract: true
    odigo.factory.userbeanwithtemplate:
        class: %odigo.factory.userbeanwithtemplate.class%
        parent: odigo.factory.abstract
        arguments: [ "@odigo.factory.userskillbeanwithtemplate" ]
    odigo.factory.userskillbeanwithtemplate:
        class: %odigo.factory.userskillbeanwithtemplate.class%
        parent: odigo.factory.abstract
    odigo.factory.userbean:
        class: %odigo.factory.userbean.class%
        parent: odigo.factory.abstract
        arguments: [ "@odigo.factory.userskillbean" ]
    odigo.factory.userskillbean:
        class: %odigo.factory.userskillbean.class%
        parent: odigo.factory.abstract
    odigo.factory.createagent:
        class: %odigo.factory.createagent.class%
        parent: odigo.factory.abstract
    odigo.factory.deleteuser:
        class: %odigo.factory.deleteuser.class%
        parent: odigo.factory.abstract
    odigo.factory.createwithtemplate:
        class: %odigo.factory.createwithtemplate.class%
        parent: odigo.factory.abstract
    odigo.factory.export:
        class: %odigo.factory.export.class%
        parent: odigo.factory.abstract
    odigo.service.client:
        class: OdigoBundle\Services\OdigoClientService
        arguments: [ "@odigo.factory.userbean", "@odigo.factory.userbeanwithtemplate" , "@odigo.factory.createagent" , "@odigo.factory.createwithtemplate" , "@odigo.factory.deleteuser", "@odigo.factory.export" ]