odigo:
    resource: "@OdigoBundle/Resources/config/routing.yml"
    prefix:   /

general:
    resource: "@GeneralBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
